### ISSUE TITLE
example using as an external OIDC Identity Provider (IDP)

### ISSUE THREAD

**Issue by c-nv-s** [authorizerdev/docs#55]
as far as I understand Authorizer can also be used as an external Identity provider for other apps using OIDC, but I cannot find an example in the docs as to what values from Authorizer to use in the configuration of the other app.
Typically you would need these values e.g. if using Google as an IDP:
```
callback_urls: ["http://localhost:8000/v1beta1/auth/callback"]
oidc_config:
  google:
    client_id: "xxxxx.apps.googleusercontent.com"
    client_secret: "xxxxx"
    issuer_url: "https://accounts.google.com"
```
I think an example demonstrating the Authorizer equivalent should be in the docs.
